Schlogl = dmschlogl odmschlogl aschlogl

all: $(Schlogl)
dmschlogl:
	cd ./DM; make;

odmschlogl:
	cd ./ODM; make;

aschlogl:
	cd ./ASCHLOGL; make;

clean:
	cd ./DM; make clean;
	cd ./ODM; make clean;
