mosmlc -c Version.sig
mosmlc -c Version.sml
mosmlc -c Help.sig
mosmlc -c Help.sml
mosmlc -c JobName.sig
mosmlc -c JobName.sml
mosmlc -c LocalTime.sml
mosmlc -c Reporting.sig
mosmlc -c Reporting.sml
mosmlc -c Error.sig
mosmlc -c Error.sml
mosmlc -c Debugging.sig
mosmlc -c Debugging.sml
mosmlc -c Options.sig
mosmlc -c Options.sml
mosmlc -c FileUtils.sig
mosmlc -c FileUtils.sml
mosmlc -c Files.sig
mosmlc -c Files.sml
mosmlc -c HashTable.sig
mosmlc -c HashTable.sml
mosmlc -c PepaNets.sig
mosmlc -c PepaNets.sml
mosmlc -c Lexer.sig
mosmlc -c Lexer.sml
mosmlc -c Sort.sig
mosmlc -c Sort.sml
mosmlc -c Prettyprinter.sig
mosmlc -c Prettyprinter.sml
mosmlc -c XMLPrettyprinter.sig
mosmlc -c XMLPrettyprinter.sml
mosmlc -c Parser.sig
mosmlc -c Parser.sml
mosmlc -c Semantic.sig
mosmlc -c Semantic.sml
mosmlc -c Bridge.sig
mosmlc -c Bridge.sml
mosmlc -c Table.sig
mosmlc -c Table.sml
mosmlc -c Branching.sig
mosmlc -c Branching.sml
mosmlc -c Statespace.sig
mosmlc -c Statespace.sml
mosmlc -c Arcs.sig
mosmlc -c Arcs.sml
mosmlc -c DerivativeSets.sig
mosmlc -c DerivativeSets.sml
mosmlc -c Cell.sig
mosmlc -c Cell.sml
mosmlc -c Markings.sig
mosmlc -c Markings.sml
mosmlc -c Priorities.sig
mosmlc -c Priorities.sml
mosmlc -c Environment.sig
mosmlc -c Environment.sml
mosmlc -c Derivatives.sig
mosmlc -c Derivatives.sml
mosmlc -c Aggregate.sig
mosmlc -c Aggregate.sml
mosmlc -c Graph.sig
mosmlc -c Graph.sml
mosmlc -c Folding.sig
mosmlc -c Folding.sml
mosmlc -c Primes.sig
mosmlc -c Primes.sml
mosmlc -c Listings.sig
mosmlc -c Listings.sml
mosmlc -c Alphabets.sig
mosmlc -c Alphabets.sml
mosmlc -c Compiler.sig
mosmlc -c Compiler.sml
mosmlc -c PWB.sig
mosmlc -c PWB.sml
mosmlc -standalone -o pwb mosmlpwb.sml
