TESTS = Dimer Schlogl Heatshock 

all: $(TESTS)

Dimer: 
	cd ./dimer; make; 

Schlogl: 
	cd ./schlogl; make; 

Heatshock: 
	cd ./heatshock; make; 

clean: 
	cd ./dimer; make clean; 
	cd ./schlogl; make clean; 
	cd ./heatshock; make clean; 

