#      StochKit (beta version)
#      All Rights Reserved.
#
#       GNU g++ makefile
#

# 1) First please decide whether or not you will use Lapack (Fortran) 
#    as linear solveror. If so, please provide the directory of lapack 
#    libs and assign the corresponding libraries to ALL_LAPACK_LIB. 
#    LAPACK can be downloaded from netlib. 

#MODIFIED BY HONGLI 1/31 for remove the SPRNG


#LAPACKOPTION = USELAPACK

LAPACKOPTION = NOTUSELAPACK
#SPRNGOPTION = _NO_SPRNG
SPRNGOPTION = _USE_SPRNG

#MPIOPTION = USE_MPI
MPIOPTION = NO_MPI


#
# Linux
#
# BLAS_LIB = $(HOME)/lib/blas_LINUX.a
# LAPACK_LIB = $(HOME)/lib/lapack_LINUX.a
# FLIBS = -lm -lg2c
#
# Sun
#
# FLIBS =  -lsunperf -lF77  -lm

# ALL_LAPACK_LIB =  $(LAPACK_LIB) $(BLAS_LIB) $(FLIBS)
ALL_LAPACK_LIB = 
# If lapack is not used, leave ALL_LAPACK_LIB empty. 

# 2) Describe your C++ compiler and platform  (tested only on Linux with GNU g++ )
#

CPP = g++
C = gcc
SSPACK_DIR = ${CSE_CPP_HOME}
CSE_MATH = ${CSE_CPP_HOME}/Math
CSE_STOCHRXN = ${CSE_CPP_HOME}/StochRxn
SPRNG_DIR = ${CSE_MATH}/sprng2.0
#SPRNG_DIR =
#APP_DIR = ${CSE_CPP_HOME}/test/tdimer

INCLUDE_DIRS = -I${CSE_MATH} -I${CSE_STOCHRXN} -I${SPRNG_DIR}/include#-I$(APP_DIR)
CPP_CONFIG = -DNDEBUG -O3 -Wall -ansi -pedantic -D${LAPACKOPTION} -D$(SPRNGOPTION)
CPP_OPTIONS = ${CPP_CONFIG} ${INCLUDE_DIRS}

LINK_DIRS = -L${CSE_MATH} -L${CSE_STOCHRXN} -L${SPRNG_DIR}/lib #-L$(APP_DIR)
LINK_LIBS =  -lCSE_StochRxn -lCSE_Math -lsprng
#LINK_LIBS =  -lCSE_StochRxn -lCSE_Math #-lSTAPP

LINK_OPTIONS = ${LINK_DIRS} ${LINK_LIBS} ${ALL_LAPACK_LIB} -lm

#---------------[ end of makefile.config ]-----------------------
