DIMER_DIR =  DIMER
SCHLOGL_DIR =  SHCLOGL
HSR_DIR =  HSR

TS = Dimer Schlogl Heatshock 

all: $(TS)

Dimer: 
	cd ./DIMER; make; 

Schlogl: 
	cd ./SCHLOGL; make; 

Heatshock: 
	cd ./HSR; make; 

clean: 
	cd ./DIMER; make clean;
	cd ./SCHLOGL; make clean;
	cd ./HSR; make clean;
